spring.application.name=credihub-payment-service
server.port=8081
spring.profiles.default=dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
payment.service.api-key=${PAYMENT_SERVICE_API_KEY}
app.base-url=${PAYMENT_BASE_URL}
credihub.base-url=${CREDIHUB_BASE_URL}