spring.datasource.url=jdbc:mysql://credihub2026.mysql.database.azure.com:3306/credihub_payment?sslMode=REQUIRED&serverTimezone=UTC
spring.datasource.username=credihubadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver